# Generated by Django 3.1.7 on 2021-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct_denoise', '0002_auto_20210430_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='userauthmodel',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
