# Generated by Django 3.1.7 on 2021-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct_denoise', '0003_auto_20210430_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
