# Generated by Django 3.1.7 on 2021-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct_denoise', '0004_auto_20210430_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAuthModel',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
    ]
