# Generated by Django 3.1.7 on 2021-05-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct_denoise', '0005_signupauthmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='signupauthmodel',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userauthmodel',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
