# Generated by Django 3.2.3 on 2021-05-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct_denoise', '0006_auto_20210505_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerifyModel',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=8)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SignupAuthModel',
        ),
    ]
